version: "3.9"

services:
  api-gateway:
    build: ./services/api_gateway
    ports:
      - "8080:8000"
    environment:
      TASK_SERVICE_URLS: http://task-service:8000
      DOC_SERVICE_URLS: http://doc-service:8000
      REMINDER_SERVICE_URLS: http://reminder-service:8000
      BOT_SERVICE_URLS: http://bot:8000
    depends_on:
      - bot
      - task-service
      - doc-service
      - reminder-service

  bot:
    build: ./services/bot
    environment:
      TASK_SERVICE_URL: http://task-service:8000
      DOC_SERVICE_URL: http://doc-service:8000
    depends_on:
      - task-service
      - doc-service

  task-service:
    build: ./services/task_service
    environment:
      DATABASE_URL: postgres://tasker:tasker@db:5432/tasker
    depends_on:
      - db

  doc-service:
    build: ./services/doc_service
  reminder-service:
    build: ./services/reminder_service
    depends_on:
      - task-service

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tasker
      POSTGRES_PASSWORD: tasker
      POSTGRES_DB: tasker
    ports:
      - "5432:5432"

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  object-store:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"